### ISSUE TITLE
RCON Bug

### ISSUE THREAD

**Issue by SwordSWD** [momo5502/boiii#207]
So I tried IW4MAdmin with BOIII after I modify the parser it shows the server but unknown gamemode and shows no activity when a player joins in. Mostly here for a feature request or bug 

`[2023-02-20 00:29:12.829  WRN] Non success response code from master is "BadRequest", message is {"message": {"servers": {"0": {"gametype": ["invalid gametype"]}}}}` - Error from IW4MAdmin

![image](https://user-images.githubusercontent.com/62721069/220019965-fa754382-e724-492f-a767-cd878726d423.png)
What it shows

**Comment by momo5502** [comment]
Implementing rcon is really more a feature i think, thank a bug

**Comment by diamante0018** [comment]
try the parser i pr to iw4m yesterday

**Comment by SwordSWD** [comment]
Okay I will later today.

**Comment by SwordSWD** [comment]
`[2023-02-22 10:55:55.169  FTL] Failed to initialize IW4MAdmin
SharedLibraryCore.Exceptions.RConException: Unexpected response header from server
   at Integrations.Cod.CodRConConnection.ValidateResponse(QueryType type, String responseString)
   at Integrations.Cod.CodRConConnection.SendQueryAsyncInternal(QueryType type, String parameters, CancellationToken token)
   at Integrations.Cod.CodRConConnection.SendQueryAsync(QueryType type, String parameters, CancellationToken token)
   at IW4MAdmin.Application.RConParsers.BaseRConParser.GetDvarAsync[T](IRConConnection connection, String dvarName, T fallbackValue, CancellationToken token)
   at SharedLibraryCore.Utilities.GetDvarAsync[T](Server server, String dvarName, T fallbackValue, CancellationToken token)
   at SharedLibraryCore.Utilities.GetMappedDvarValueOrDefaultAsync[T](Server server, String dvarName, String infoResponseName, IDictionary`2 infoResponse, T overrideDefault, CancellationToken token)
   at IW4MAdmin.IW4MServer.Initialize()
   at IW4MAdmin.Application.ApplicationManager.<>c__DisplayClass89_0.<<InitializeServers>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
   at IW4MAdmin.Application.ApplicationManager.InitializeServers()
   at IW4MAdmin.Application.ApplicationManager.Init()
   at IW4MAdmin.Application.Program.LaunchAsync(String[] args)
Fatal error during initialization
Unexpected response header from server`

with the boiiiparser

**Comment by diamante0018** [comment]
Can you type status in the dedicated server console and post it here in a code block?

**Comment by SwordSWD** [comment]
The new parser Future made fixed the issue with iw4madmin and it doesn't have anything to do with BOIII so safe to say that this can be closed now.
